/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { SceneWrapper } from "./scene-wrapper";

type GLTFResult = GLTF & {
  nodes: {
    mesh0_mesh: THREE.Mesh;
    mesh0_mesh_1: THREE.Mesh;
    mesh0_mesh_2: THREE.Mesh;
    mesh0_mesh_3: THREE.Mesh;
    mesh0_mesh_4: THREE.Mesh;
    mesh0_mesh_5: THREE.Mesh;
    mesh0_mesh_6: THREE.Mesh;
    mesh0_mesh_7: THREE.Mesh;
    mesh0_mesh_8: THREE.Mesh;
    mesh0_mesh_9: THREE.Mesh;
    mesh0_mesh_10: THREE.Mesh;
    mesh0_mesh_11: THREE.Mesh;
    mesh0_mesh_12: THREE.Mesh;
    mesh0_mesh_13: THREE.Mesh;
    mesh0_mesh_14: THREE.Mesh;
    mesh0_mesh_15: THREE.Mesh;
    mesh0_mesh_16: THREE.Mesh;
    mesh0_mesh_17: THREE.Mesh;
    mesh0_mesh_18: THREE.Mesh;
    mesh0_mesh_19: THREE.Mesh;
    mesh0_mesh_20: THREE.Mesh;
    mesh0_mesh_21: THREE.Mesh;
    mesh0_mesh_22: THREE.Mesh;
    mesh0_mesh_23: THREE.Mesh;
    mesh0_mesh_24: THREE.Mesh;
    mesh0_mesh_25: THREE.Mesh;
    mesh0_mesh_26: THREE.Mesh;
    mesh0_mesh_27: THREE.Mesh;
    mesh0_mesh_28: THREE.Mesh;
    mesh0_mesh_29: THREE.Mesh;
    mesh0_mesh_30: THREE.Mesh;
    mesh0_mesh_31: THREE.Mesh;
    mesh0_mesh_32: THREE.Mesh;
    mesh0_mesh_33: THREE.Mesh;
    mesh0_mesh_34: THREE.Mesh;
    mesh0_mesh_35: THREE.Mesh;
    mesh0_mesh_36: THREE.Mesh;
    mesh0_mesh_37: THREE.Mesh;
    mesh0_mesh_38: THREE.Mesh;
    mesh0_mesh_39: THREE.Mesh;
    mesh0_mesh_40: THREE.Mesh;
    mesh0_mesh_41: THREE.Mesh;
    mesh0_mesh_42: THREE.Mesh;
    mesh0_mesh_43: THREE.Mesh;
    mesh0_mesh_44: THREE.Mesh;
    mesh0_mesh_45: THREE.Mesh;
    mesh0_mesh_46: THREE.Mesh;
    mesh0_mesh_47: THREE.Mesh;
    mesh48_mesh: THREE.Mesh;
    mesh48_mesh_1: THREE.Mesh;
    mesh48_mesh_2: THREE.Mesh;
    mesh48_mesh_3: THREE.Mesh;
    mesh48_mesh_4: THREE.Mesh;
    mesh48_mesh_5: THREE.Mesh;
    mesh48_mesh_6: THREE.Mesh;
    mesh48_mesh_7: THREE.Mesh;
    mesh48_mesh_8: THREE.Mesh;
    mesh48_mesh_9: THREE.Mesh;
    mesh48_mesh_10: THREE.Mesh;
    mesh48_mesh_11: THREE.Mesh;
    mesh48_mesh_12: THREE.Mesh;
    mesh48_mesh_13: THREE.Mesh;
    mesh48_mesh_14: THREE.Mesh;
    mesh48_mesh_15: THREE.Mesh;
    mesh48_mesh_16: THREE.Mesh;
    mesh48_mesh_17: THREE.Mesh;
    mesh48_mesh_18: THREE.Mesh;
    mesh48_mesh_19: THREE.Mesh;
    mesh48_mesh_20: THREE.Mesh;
    mesh48_mesh_21: THREE.Mesh;
    mesh48_mesh_22: THREE.Mesh;
    mesh48_mesh_23: THREE.Mesh;
    mesh48_mesh_24: THREE.Mesh;
    mesh48_mesh_25: THREE.Mesh;
    mesh48_mesh_26: THREE.Mesh;
    mesh48_mesh_27: THREE.Mesh;
    mesh48_mesh_28: THREE.Mesh;
    mesh48_mesh_29: THREE.Mesh;
    mesh48_mesh_30: THREE.Mesh;
    mesh48_mesh_31: THREE.Mesh;
    mesh48_mesh_32: THREE.Mesh;
    mesh48_mesh_33: THREE.Mesh;
    mesh48_mesh_34: THREE.Mesh;
    mesh48_mesh_35: THREE.Mesh;
    mesh48_mesh_36: THREE.Mesh;
    mesh48_mesh_37: THREE.Mesh;
    mesh48_mesh_38: THREE.Mesh;
    mesh48_mesh_39: THREE.Mesh;
    mesh48_mesh_40: THREE.Mesh;
    mesh48_mesh_41: THREE.Mesh;
    mesh48_mesh_42: THREE.Mesh;
    mesh48_mesh_43: THREE.Mesh;
    mesh48_mesh_44: THREE.Mesh;
    mesh48_mesh_45: THREE.Mesh;
    mesh48_mesh_46: THREE.Mesh;
    mesh48_mesh_47: THREE.Mesh;
    mesh48_mesh_48: THREE.Mesh;
    mesh48_mesh_49: THREE.Mesh;
    mesh48_mesh_50: THREE.Mesh;
    mesh48_mesh_51: THREE.Mesh;
    mesh48_mesh_52: THREE.Mesh;
    mesh48_mesh_53: THREE.Mesh;
    mesh48_mesh_54: THREE.Mesh;
    mesh48_mesh_55: THREE.Mesh;
    mesh48_mesh_56: THREE.Mesh;
    mesh48_mesh_57: THREE.Mesh;
    mesh48_mesh_58: THREE.Mesh;
    mesh48_mesh_59: THREE.Mesh;
    mesh48_mesh_60: THREE.Mesh;
    mesh48_mesh_61: THREE.Mesh;
    mesh48_mesh_62: THREE.Mesh;
    mesh48_mesh_63: THREE.Mesh;
    mesh112_mesh: THREE.Mesh;
    mesh112_mesh_1: THREE.Mesh;
    mesh112_mesh_2: THREE.Mesh;
    mesh112_mesh_3: THREE.Mesh;
    mesh112_mesh_4: THREE.Mesh;
    mesh112_mesh_5: THREE.Mesh;
    mesh112_mesh_6: THREE.Mesh;
    mesh112_mesh_7: THREE.Mesh;
    mesh112_mesh_8: THREE.Mesh;
    mesh112_mesh_9: THREE.Mesh;
    mesh112_mesh_10: THREE.Mesh;
    mesh112_mesh_11: THREE.Mesh;
    mesh112_mesh_12: THREE.Mesh;
    mesh112_mesh_13: THREE.Mesh;
    mesh112_mesh_14: THREE.Mesh;
    mesh112_mesh_15: THREE.Mesh;
    mesh112_mesh_16: THREE.Mesh;
    mesh112_mesh_17: THREE.Mesh;
    mesh112_mesh_18: THREE.Mesh;
    mesh112_mesh_19: THREE.Mesh;
    mesh112_mesh_20: THREE.Mesh;
    mesh112_mesh_21: THREE.Mesh;
    mesh112_mesh_22: THREE.Mesh;
    mesh112_mesh_23: THREE.Mesh;
    mesh112_mesh_24: THREE.Mesh;
    mesh112_mesh_25: THREE.Mesh;
    mesh112_mesh_26: THREE.Mesh;
    mesh112_mesh_27: THREE.Mesh;
    mesh112_mesh_28: THREE.Mesh;
    mesh112_mesh_29: THREE.Mesh;
    mesh112_mesh_30: THREE.Mesh;
    mesh112_mesh_31: THREE.Mesh;
    mesh112_mesh_32: THREE.Mesh;
    mesh112_mesh_33: THREE.Mesh;
    mesh112_mesh_34: THREE.Mesh;
    mesh112_mesh_35: THREE.Mesh;
    mesh112_mesh_36: THREE.Mesh;
    mesh112_mesh_37: THREE.Mesh;
    mesh112_mesh_38: THREE.Mesh;
    mesh112_mesh_39: THREE.Mesh;
    mesh112_mesh_40: THREE.Mesh;
    mesh112_mesh_41: THREE.Mesh;
    mesh112_mesh_42: THREE.Mesh;
    mesh112_mesh_43: THREE.Mesh;
    mesh112_mesh_44: THREE.Mesh;
    mesh112_mesh_45: THREE.Mesh;
    mesh112_mesh_46: THREE.Mesh;
    mesh112_mesh_47: THREE.Mesh;
    mesh160_mesh: THREE.Mesh;
    mesh160_mesh_1: THREE.Mesh;
    mesh160_mesh_2: THREE.Mesh;
    mesh160_mesh_3: THREE.Mesh;
    mesh160_mesh_4: THREE.Mesh;
    mesh160_mesh_5: THREE.Mesh;
    mesh160_mesh_6: THREE.Mesh;
    mesh160_mesh_7: THREE.Mesh;
    mesh160_mesh_8: THREE.Mesh;
    mesh160_mesh_9: THREE.Mesh;
    mesh160_mesh_10: THREE.Mesh;
    mesh160_mesh_11: THREE.Mesh;
    mesh160_mesh_12: THREE.Mesh;
    mesh160_mesh_13: THREE.Mesh;
    mesh160_mesh_14: THREE.Mesh;
    mesh160_mesh_15: THREE.Mesh;
    mesh160_mesh_16: THREE.Mesh;
    mesh160_mesh_17: THREE.Mesh;
    mesh160_mesh_18: THREE.Mesh;
    mesh160_mesh_19: THREE.Mesh;
    mesh160_mesh_20: THREE.Mesh;
    mesh160_mesh_21: THREE.Mesh;
    mesh160_mesh_22: THREE.Mesh;
    mesh160_mesh_23: THREE.Mesh;
    mesh160_mesh_24: THREE.Mesh;
    mesh160_mesh_25: THREE.Mesh;
    mesh160_mesh_26: THREE.Mesh;
    mesh160_mesh_27: THREE.Mesh;
    mesh160_mesh_28: THREE.Mesh;
    mesh160_mesh_29: THREE.Mesh;
    mesh160_mesh_30: THREE.Mesh;
    mesh160_mesh_31: THREE.Mesh;
    mesh160_mesh_32: THREE.Mesh;
    mesh160_mesh_33: THREE.Mesh;
    mesh160_mesh_34: THREE.Mesh;
    mesh160_mesh_35: THREE.Mesh;
    mesh160_mesh_36: THREE.Mesh;
    mesh160_mesh_37: THREE.Mesh;
    mesh160_mesh_38: THREE.Mesh;
    mesh160_mesh_39: THREE.Mesh;
    mesh160_mesh_40: THREE.Mesh;
    mesh160_mesh_41: THREE.Mesh;
    mesh160_mesh_42: THREE.Mesh;
    mesh160_mesh_43: THREE.Mesh;
    mesh160_mesh_44: THREE.Mesh;
    mesh160_mesh_45: THREE.Mesh;
    mesh160_mesh_46: THREE.Mesh;
    mesh160_mesh_47: THREE.Mesh;
    mesh160_mesh_48: THREE.Mesh;
    mesh160_mesh_49: THREE.Mesh;
    mesh160_mesh_50: THREE.Mesh;
    mesh160_mesh_51: THREE.Mesh;
    mesh160_mesh_52: THREE.Mesh;
    mesh160_mesh_53: THREE.Mesh;
    mesh160_mesh_54: THREE.Mesh;
    mesh160_mesh_55: THREE.Mesh;
    mesh160_mesh_56: THREE.Mesh;
    mesh160_mesh_57: THREE.Mesh;
    mesh160_mesh_58: THREE.Mesh;
    mesh160_mesh_59: THREE.Mesh;
    mesh160_mesh_60: THREE.Mesh;
    mesh160_mesh_61: THREE.Mesh;
    mesh160_mesh_62: THREE.Mesh;
    mesh160_mesh_63: THREE.Mesh;
    mesh224_mesh: THREE.Mesh;
    mesh224_mesh_1: THREE.Mesh;
    mesh224_mesh_2: THREE.Mesh;
    mesh224_mesh_3: THREE.Mesh;
    mesh224_mesh_4: THREE.Mesh;
    mesh224_mesh_5: THREE.Mesh;
    mesh224_mesh_6: THREE.Mesh;
    mesh224_mesh_7: THREE.Mesh;
    mesh224_mesh_8: THREE.Mesh;
    mesh224_mesh_9: THREE.Mesh;
    mesh224_mesh_10: THREE.Mesh;
    mesh224_mesh_11: THREE.Mesh;
    mesh224_mesh_12: THREE.Mesh;
    mesh224_mesh_13: THREE.Mesh;
    mesh224_mesh_14: THREE.Mesh;
    mesh224_mesh_15: THREE.Mesh;
    mesh224_mesh_16: THREE.Mesh;
    mesh224_mesh_17: THREE.Mesh;
    mesh224_mesh_18: THREE.Mesh;
    mesh224_mesh_19: THREE.Mesh;
    mesh224_mesh_20: THREE.Mesh;
    mesh224_mesh_21: THREE.Mesh;
    mesh224_mesh_22: THREE.Mesh;
    mesh224_mesh_23: THREE.Mesh;
    mesh224_mesh_24: THREE.Mesh;
    mesh224_mesh_25: THREE.Mesh;
    mesh224_mesh_26: THREE.Mesh;
    mesh224_mesh_27: THREE.Mesh;
    mesh224_mesh_28: THREE.Mesh;
    mesh224_mesh_29: THREE.Mesh;
    mesh224_mesh_30: THREE.Mesh;
    mesh224_mesh_31: THREE.Mesh;
    mesh224_mesh_32: THREE.Mesh;
    mesh224_mesh_33: THREE.Mesh;
    mesh224_mesh_34: THREE.Mesh;
    mesh224_mesh_35: THREE.Mesh;
    mesh224_mesh_36: THREE.Mesh;
    mesh224_mesh_37: THREE.Mesh;
    mesh224_mesh_38: THREE.Mesh;
    mesh224_mesh_39: THREE.Mesh;
    mesh224_mesh_40: THREE.Mesh;
    mesh224_mesh_41: THREE.Mesh;
    mesh224_mesh_42: THREE.Mesh;
    mesh224_mesh_43: THREE.Mesh;
    mesh224_mesh_44: THREE.Mesh;
    mesh224_mesh_45: THREE.Mesh;
    mesh224_mesh_46: THREE.Mesh;
    mesh224_mesh_47: THREE.Mesh;
    mesh224_mesh_48: THREE.Mesh;
    mesh224_mesh_49: THREE.Mesh;
    mesh224_mesh_50: THREE.Mesh;
    mesh224_mesh_51: THREE.Mesh;
    mesh224_mesh_52: THREE.Mesh;
    mesh224_mesh_53: THREE.Mesh;
    mesh224_mesh_54: THREE.Mesh;
    mesh224_mesh_55: THREE.Mesh;
    mesh224_mesh_56: THREE.Mesh;
    mesh224_mesh_57: THREE.Mesh;
    mesh224_mesh_58: THREE.Mesh;
    mesh224_mesh_59: THREE.Mesh;
    mesh224_mesh_60: THREE.Mesh;
    mesh224_mesh_61: THREE.Mesh;
    mesh224_mesh_62: THREE.Mesh;
    mesh224_mesh_63: THREE.Mesh;
    mesh224_mesh_64: THREE.Mesh;
    mesh224_mesh_65: THREE.Mesh;
    mesh224_mesh_66: THREE.Mesh;
    mesh224_mesh_67: THREE.Mesh;
    mesh224_mesh_68: THREE.Mesh;
    mesh224_mesh_69: THREE.Mesh;
    mesh224_mesh_70: THREE.Mesh;
    mesh224_mesh_71: THREE.Mesh;
    mesh224_mesh_72: THREE.Mesh;
    mesh224_mesh_73: THREE.Mesh;
    mesh224_mesh_74: THREE.Mesh;
    mesh224_mesh_75: THREE.Mesh;
    mesh224_mesh_76: THREE.Mesh;
    mesh224_mesh_77: THREE.Mesh;
    mesh224_mesh_78: THREE.Mesh;
    mesh224_mesh_79: THREE.Mesh;
    mesh224_mesh_80: THREE.Mesh;
    mesh224_mesh_81: THREE.Mesh;
    mesh224_mesh_82: THREE.Mesh;
    mesh224_mesh_83: THREE.Mesh;
    mesh224_mesh_84: THREE.Mesh;
    mesh224_mesh_85: THREE.Mesh;
    mesh224_mesh_86: THREE.Mesh;
    mesh224_mesh_87: THREE.Mesh;
    mesh224_mesh_88: THREE.Mesh;
    mesh224_mesh_89: THREE.Mesh;
    mesh224_mesh_90: THREE.Mesh;
    mesh224_mesh_91: THREE.Mesh;
    mesh224_mesh_92: THREE.Mesh;
    mesh224_mesh_93: THREE.Mesh;
    mesh224_mesh_94: THREE.Mesh;
    mesh224_mesh_95: THREE.Mesh;
    mesh224_mesh_96: THREE.Mesh;
    mesh224_mesh_97: THREE.Mesh;
    mesh224_mesh_98: THREE.Mesh;
    mesh224_mesh_99: THREE.Mesh;
    mesh224_mesh_100: THREE.Mesh;
    mesh224_mesh_101: THREE.Mesh;
    mesh224_mesh_102: THREE.Mesh;
    mesh224_mesh_103: THREE.Mesh;
    mesh224_mesh_104: THREE.Mesh;
    mesh224_mesh_105: THREE.Mesh;
    mesh224_mesh_106: THREE.Mesh;
    mesh224_mesh_107: THREE.Mesh;
    mesh224_mesh_108: THREE.Mesh;
    mesh224_mesh_109: THREE.Mesh;
    mesh224_mesh_110: THREE.Mesh;
    mesh224_mesh_111: THREE.Mesh;
    mesh224_mesh_112: THREE.Mesh;
    mesh224_mesh_113: THREE.Mesh;
    mesh224_mesh_114: THREE.Mesh;
    mesh224_mesh_115: THREE.Mesh;
    mesh224_mesh_116: THREE.Mesh;
    mesh224_mesh_117: THREE.Mesh;
  };
  materials: {
    ["0.086275_0.321569_0.580392_0.000000_0.000000"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/baja_seat.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_1.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_2.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_3.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_4.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_5.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_6.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_7.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_8.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_9.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_10.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_11.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_12.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_13.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_14.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_15.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_16.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_17.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_18.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_19.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_20.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_21.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_22.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_23.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_24.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_25.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_26.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_27.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_28.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_29.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_30.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_31.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_32.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_33.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_34.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_35.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_36.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_37.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_38.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_39.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_40.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_41.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_42.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_43.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_44.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_45.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_46.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_47.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_1.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_2.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_3.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_4.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_5.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_6.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_7.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_8.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_9.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_10.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_11.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_12.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_13.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_14.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_15.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_16.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_17.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_18.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_19.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_20.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_21.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_22.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_23.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_24.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_25.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_26.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_27.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_28.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_29.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_30.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_31.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_32.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_33.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_34.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_35.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_36.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_37.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_38.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_39.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_40.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_41.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_42.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_43.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_44.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_45.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_46.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_47.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_48.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_49.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_50.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_51.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_52.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_53.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_54.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_55.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_56.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_57.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_58.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_59.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_60.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_61.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_62.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh48_mesh_63.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_1.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_2.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_3.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_4.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_5.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_6.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_7.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_8.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_9.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_10.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_11.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_12.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_13.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_14.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_15.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_16.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_17.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_18.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_19.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_20.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_21.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_22.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_23.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_24.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_25.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_26.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_27.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_28.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_29.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_30.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_31.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_32.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_33.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_34.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_35.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_36.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_37.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_38.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_39.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_40.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_41.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_42.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_43.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_44.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_45.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_46.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh112_mesh_47.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_1.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_2.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_3.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_4.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_5.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_6.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_7.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_8.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_9.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_10.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_11.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_12.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_13.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_14.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_15.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_16.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_17.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_18.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_19.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_20.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_21.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_22.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_23.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_24.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_25.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_26.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_27.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_28.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_29.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_30.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_31.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_32.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_33.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_34.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_35.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_36.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_37.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_38.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_39.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_40.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_41.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_42.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_43.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_44.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_45.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_46.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_47.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_48.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_49.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_50.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_51.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_52.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_53.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_54.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_55.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_56.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_57.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_58.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_59.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_60.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_61.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_62.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh160_mesh_63.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_1.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_2.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_3.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_4.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_5.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_6.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_7.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_8.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_9.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_10.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_11.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_12.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_13.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_14.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_15.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_16.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_17.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_18.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_19.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_20.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_21.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_22.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_23.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_24.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_25.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_26.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_27.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_28.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_29.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_30.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_31.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_32.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_33.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_34.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_35.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_36.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_37.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_38.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_39.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_40.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_41.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_42.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_43.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_44.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_45.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_46.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_47.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_48.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_49.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_50.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_51.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_52.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_53.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_54.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_55.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_56.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_57.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_58.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_59.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_60.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_61.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_62.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_63.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_64.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_65.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_66.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_67.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_68.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_69.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_70.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_71.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_72.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_73.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_74.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_75.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_76.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_77.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_78.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_79.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_80.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_81.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_82.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_83.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_84.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_85.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_86.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_87.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_88.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_89.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_90.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_91.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_92.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_93.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_94.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_95.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_96.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_97.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_98.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_99.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_100.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_101.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_102.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_103.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_104.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_105.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_106.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_107.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_108.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_109.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_110.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_111.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_112.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_113.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_114.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_115.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_116.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh224_mesh_117.geometry}
        material={materials["0.086275_0.321569_0.580392_0.000000_0.000000"]}
      />
    </group>
  );
}

useGLTF.preload("/models/baja_seat.gltf");

export const Scene: React.FC = () => {
  return (
    <SceneWrapper>
      <Model />
    </SceneWrapper>
  );
};
