/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/hovercraft_mk6.gltf -t -r models -s -o src/components/models/hovercraft-mk6.tsx 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { SceneWrapper } from "./scene-wrapper";

type GLTFResult = GLTF & {
  nodes: {
    mesh0_mesh: THREE.Mesh;
    mesh0_mesh_1: THREE.Mesh;
    mesh0_mesh_2: THREE.Mesh;
    mesh0_mesh_3: THREE.Mesh;
    mesh0_mesh_4: THREE.Mesh;
    mesh0_mesh_5: THREE.Mesh;
    mesh0_mesh_6: THREE.Mesh;
    mesh0_mesh_7: THREE.Mesh;
    mesh0_mesh_8: THREE.Mesh;
    mesh0_mesh_9: THREE.Mesh;
    mesh0_mesh_10: THREE.Mesh;
    mesh0_mesh_11: THREE.Mesh;
    mesh0_mesh_12: THREE.Mesh;
    mesh0_mesh_13: THREE.Mesh;
    mesh0_mesh_14: THREE.Mesh;
    mesh0_mesh_15: THREE.Mesh;
    mesh0_mesh_16: THREE.Mesh;
    mesh0_mesh_17: THREE.Mesh;
    mesh0_mesh_18: THREE.Mesh;
    mesh0_mesh_19: THREE.Mesh;
    mesh0_mesh_20: THREE.Mesh;
    mesh0_mesh_21: THREE.Mesh;
    mesh0_mesh_22: THREE.Mesh;
    mesh0_mesh_23: THREE.Mesh;
    mesh0_mesh_24: THREE.Mesh;
    mesh0_mesh_25: THREE.Mesh;
    mesh0_mesh_26: THREE.Mesh;
    mesh0_mesh_27: THREE.Mesh;
    mesh0_mesh_28: THREE.Mesh;
    mesh0_mesh_29: THREE.Mesh;
    mesh0_mesh_30: THREE.Mesh;
    mesh0_mesh_31: THREE.Mesh;
    mesh0_mesh_32: THREE.Mesh;
    mesh0_mesh_33: THREE.Mesh;
    mesh0_mesh_34: THREE.Mesh;
    mesh0_mesh_35: THREE.Mesh;
    mesh0_mesh_36: THREE.Mesh;
    mesh0_mesh_37: THREE.Mesh;
    mesh0_mesh_38: THREE.Mesh;
    mesh0_mesh_39: THREE.Mesh;
    mesh0_mesh_40: THREE.Mesh;
    mesh0_mesh_41: THREE.Mesh;
    mesh0_mesh_42: THREE.Mesh;
    mesh0_mesh_43: THREE.Mesh;
    mesh0_mesh_44: THREE.Mesh;
    mesh0_mesh_45: THREE.Mesh;
    mesh0_mesh_46: THREE.Mesh;
    mesh0_mesh_47: THREE.Mesh;
    mesh0_mesh_48: THREE.Mesh;
    mesh0_mesh_49: THREE.Mesh;
    mesh0_mesh_50: THREE.Mesh;
    mesh0_mesh_51: THREE.Mesh;
    mesh0_mesh_52: THREE.Mesh;
    mesh0_mesh_53: THREE.Mesh;
    mesh0_mesh_54: THREE.Mesh;
    mesh0_mesh_55: THREE.Mesh;
    mesh0_mesh_56: THREE.Mesh;
    mesh0_mesh_57: THREE.Mesh;
    mesh0_mesh_58: THREE.Mesh;
    mesh0_mesh_59: THREE.Mesh;
    mesh0_mesh_60: THREE.Mesh;
    mesh0_mesh_61: THREE.Mesh;
    mesh0_mesh_62: THREE.Mesh;
    mesh0_mesh_63: THREE.Mesh;
    mesh0_mesh_64: THREE.Mesh;
    mesh0_mesh_65: THREE.Mesh;
    mesh0_mesh_66: THREE.Mesh;
    mesh0_mesh_67: THREE.Mesh;
    mesh0_mesh_68: THREE.Mesh;
    mesh0_mesh_69: THREE.Mesh;
    mesh0_mesh_70: THREE.Mesh;
    mesh0_mesh_71: THREE.Mesh;
    mesh0_mesh_72: THREE.Mesh;
    mesh0_mesh_73: THREE.Mesh;
    mesh0_mesh_74: THREE.Mesh;
    mesh0_mesh_75: THREE.Mesh;
    mesh0_mesh_76: THREE.Mesh;
    mesh0_mesh_77: THREE.Mesh;
    mesh0_mesh_78: THREE.Mesh;
    mesh0_mesh_79: THREE.Mesh;
    mesh0_mesh_80: THREE.Mesh;
    mesh0_mesh_81: THREE.Mesh;
    mesh0_mesh_82: THREE.Mesh;
    mesh0_mesh_83: THREE.Mesh;
    mesh0_mesh_84: THREE.Mesh;
    mesh0_mesh_85: THREE.Mesh;
    mesh0_mesh_86: THREE.Mesh;
    mesh0_mesh_87: THREE.Mesh;
    mesh0_mesh_88: THREE.Mesh;
    mesh0_mesh_89: THREE.Mesh;
    mesh0_mesh_90: THREE.Mesh;
    mesh0_mesh_91: THREE.Mesh;
    mesh0_mesh_92: THREE.Mesh;
    mesh0_mesh_93: THREE.Mesh;
    mesh0_mesh_94: THREE.Mesh;
    mesh0_mesh_95: THREE.Mesh;
    mesh0_mesh_96: THREE.Mesh;
    mesh0_mesh_97: THREE.Mesh;
    mesh0_mesh_98: THREE.Mesh;
    mesh0_mesh_99: THREE.Mesh;
    mesh0_mesh_100: THREE.Mesh;
    mesh0_mesh_101: THREE.Mesh;
    mesh0_mesh_102: THREE.Mesh;
    mesh0_mesh_103: THREE.Mesh;
    mesh0_mesh_104: THREE.Mesh;
    mesh0_mesh_105: THREE.Mesh;
    mesh0_mesh_106: THREE.Mesh;
    mesh0_mesh_107: THREE.Mesh;
    mesh0_mesh_108: THREE.Mesh;
    mesh0_mesh_109: THREE.Mesh;
    mesh0_mesh_110: THREE.Mesh;
    mesh0_mesh_111: THREE.Mesh;
    mesh0_mesh_112: THREE.Mesh;
    mesh0_mesh_113: THREE.Mesh;
    mesh0_mesh_114: THREE.Mesh;
    mesh0_mesh_115: THREE.Mesh;
    mesh0_mesh_116: THREE.Mesh;
    mesh0_mesh_117: THREE.Mesh;
    mesh0_mesh_118: THREE.Mesh;
    mesh0_mesh_119: THREE.Mesh;
    mesh0_mesh_120: THREE.Mesh;
    mesh0_mesh_121: THREE.Mesh;
    mesh0_mesh_122: THREE.Mesh;
    mesh0_mesh_123: THREE.Mesh;
    mesh0_mesh_124: THREE.Mesh;
    mesh0_mesh_125: THREE.Mesh;
    mesh0_mesh_126: THREE.Mesh;
    mesh0_mesh_127: THREE.Mesh;
    mesh0_mesh_128: THREE.Mesh;
    mesh0_mesh_129: THREE.Mesh;
    mesh0_mesh_130: THREE.Mesh;
    mesh0_mesh_131: THREE.Mesh;
    mesh0_mesh_132: THREE.Mesh;
    mesh0_mesh_133: THREE.Mesh;
    mesh0_mesh_134: THREE.Mesh;
    mesh0_mesh_135: THREE.Mesh;
    mesh0_mesh_136: THREE.Mesh;
    mesh0_mesh_137: THREE.Mesh;
    mesh0_mesh_138: THREE.Mesh;
    mesh0_mesh_139: THREE.Mesh;
    mesh0_mesh_140: THREE.Mesh;
    mesh0_mesh_141: THREE.Mesh;
    mesh0_mesh_142: THREE.Mesh;
    mesh0_mesh_143: THREE.Mesh;
    mesh0_mesh_144: THREE.Mesh;
    mesh0_mesh_145: THREE.Mesh;
    mesh0_mesh_146: THREE.Mesh;
    mesh0_mesh_147: THREE.Mesh;
    mesh0_mesh_148: THREE.Mesh;
    mesh0_mesh_149: THREE.Mesh;
    mesh0_mesh_150: THREE.Mesh;
    mesh0_mesh_151: THREE.Mesh;
    mesh0_mesh_152: THREE.Mesh;
    mesh0_mesh_153: THREE.Mesh;
    mesh0_mesh_154: THREE.Mesh;
    mesh0_mesh_155: THREE.Mesh;
    mesh0_mesh_156: THREE.Mesh;
    mesh0_mesh_157: THREE.Mesh;
    mesh0_mesh_158: THREE.Mesh;
    mesh0_mesh_159: THREE.Mesh;
    mesh0_mesh_160: THREE.Mesh;
    mesh0_mesh_161: THREE.Mesh;
    mesh0_mesh_162: THREE.Mesh;
    mesh0_mesh_163: THREE.Mesh;
    mesh0_mesh_164: THREE.Mesh;
    mesh0_mesh_165: THREE.Mesh;
    mesh0_mesh_166: THREE.Mesh;
    mesh0_mesh_167: THREE.Mesh;
    mesh0_mesh_168: THREE.Mesh;
    mesh0_mesh_169: THREE.Mesh;
    mesh0_mesh_170: THREE.Mesh;
    mesh0_mesh_171: THREE.Mesh;
    mesh0_mesh_172: THREE.Mesh;
    mesh0_mesh_173: THREE.Mesh;
    mesh0_mesh_174: THREE.Mesh;
    mesh0_mesh_175: THREE.Mesh;
    mesh0_mesh_176: THREE.Mesh;
    mesh0_mesh_177: THREE.Mesh;
    mesh0_mesh_178: THREE.Mesh;
    mesh0_mesh_179: THREE.Mesh;
    mesh0_mesh_180: THREE.Mesh;
    mesh0_mesh_181: THREE.Mesh;
    mesh0_mesh_182: THREE.Mesh;
    mesh0_mesh_183: THREE.Mesh;
    mesh0_mesh_184: THREE.Mesh;
    mesh0_mesh_185: THREE.Mesh;
    mesh0_mesh_186: THREE.Mesh;
    mesh0_mesh_187: THREE.Mesh;
    mesh0_mesh_188: THREE.Mesh;
    mesh0_mesh_189: THREE.Mesh;
    mesh0_mesh_190: THREE.Mesh;
    mesh0_mesh_191: THREE.Mesh;
    mesh0_mesh_192: THREE.Mesh;
    mesh0_mesh_193: THREE.Mesh;
    mesh0_mesh_194: THREE.Mesh;
    mesh0_mesh_195: THREE.Mesh;
    mesh0_mesh_196: THREE.Mesh;
    mesh0_mesh_197: THREE.Mesh;
    mesh0_mesh_198: THREE.Mesh;
    mesh0_mesh_199: THREE.Mesh;
    mesh0_mesh_200: THREE.Mesh;
    mesh0_mesh_201: THREE.Mesh;
    mesh0_mesh_202: THREE.Mesh;
    mesh0_mesh_203: THREE.Mesh;
    mesh0_mesh_204: THREE.Mesh;
    mesh0_mesh_205: THREE.Mesh;
    mesh0_mesh_206: THREE.Mesh;
    mesh0_mesh_207: THREE.Mesh;
    mesh0_mesh_208: THREE.Mesh;
    mesh0_mesh_209: THREE.Mesh;
    mesh0_mesh_210: THREE.Mesh;
    mesh0_mesh_211: THREE.Mesh;
    mesh0_mesh_212: THREE.Mesh;
    mesh0_mesh_213: THREE.Mesh;
    mesh0_mesh_214: THREE.Mesh;
    mesh0_mesh_215: THREE.Mesh;
    mesh0_mesh_216: THREE.Mesh;
    mesh0_mesh_217: THREE.Mesh;
    mesh0_mesh_218: THREE.Mesh;
    mesh0_mesh_219: THREE.Mesh;
    mesh0_mesh_220: THREE.Mesh;
    mesh0_mesh_221: THREE.Mesh;
    mesh0_mesh_222: THREE.Mesh;
    mesh0_mesh_223: THREE.Mesh;
    mesh0_mesh_224: THREE.Mesh;
    mesh0_mesh_225: THREE.Mesh;
    mesh0_mesh_226: THREE.Mesh;
    mesh0_mesh_227: THREE.Mesh;
    mesh0_mesh_228: THREE.Mesh;
    mesh0_mesh_229: THREE.Mesh;
    mesh0_mesh_230: THREE.Mesh;
    mesh0_mesh_231: THREE.Mesh;
    mesh0_mesh_232: THREE.Mesh;
    mesh0_mesh_233: THREE.Mesh;
    mesh0_mesh_234: THREE.Mesh;
    mesh0_mesh_235: THREE.Mesh;
    mesh0_mesh_236: THREE.Mesh;
    mesh0_mesh_237: THREE.Mesh;
    mesh0_mesh_238: THREE.Mesh;
    mesh0_mesh_239: THREE.Mesh;
    mesh0_mesh_240: THREE.Mesh;
    mesh0_mesh_241: THREE.Mesh;
    mesh0_mesh_242: THREE.Mesh;
    mesh0_mesh_243: THREE.Mesh;
    mesh0_mesh_244: THREE.Mesh;
    mesh0_mesh_245: THREE.Mesh;
    mesh0_mesh_246: THREE.Mesh;
    mesh0_mesh_247: THREE.Mesh;
    mesh0_mesh_248: THREE.Mesh;
    mesh0_mesh_249: THREE.Mesh;
    mesh0_mesh_250: THREE.Mesh;
    mesh0_mesh_251: THREE.Mesh;
    mesh0_mesh_252: THREE.Mesh;
    mesh0_mesh_253: THREE.Mesh;
    mesh0_mesh_254: THREE.Mesh;
    mesh0_mesh_255: THREE.Mesh;
    mesh256_mesh: THREE.Mesh;
    mesh256_mesh_1: THREE.Mesh;
    mesh256_mesh_2: THREE.Mesh;
    mesh256_mesh_3: THREE.Mesh;
    mesh256_mesh_4: THREE.Mesh;
    mesh256_mesh_5: THREE.Mesh;
    mesh262_mesh: THREE.Mesh;
    mesh262_mesh_1: THREE.Mesh;
    mesh262_mesh_2: THREE.Mesh;
    mesh262_mesh_3: THREE.Mesh;
    mesh262_mesh_4: THREE.Mesh;
    mesh262_mesh_5: THREE.Mesh;
    mesh262_mesh_6: THREE.Mesh;
    mesh269_mesh: THREE.Mesh;
    mesh269_mesh_1: THREE.Mesh;
    mesh269_mesh_2: THREE.Mesh;
    mesh269_mesh_3: THREE.Mesh;
    mesh269_mesh_4: THREE.Mesh;
    mesh269_mesh_5: THREE.Mesh;
    mesh269_mesh_6: THREE.Mesh;
    mesh269_mesh_7: THREE.Mesh;
    mesh269_mesh_8: THREE.Mesh;
    mesh278_mesh: THREE.Mesh;
    mesh278_mesh_1: THREE.Mesh;
    mesh278_mesh_2: THREE.Mesh;
    mesh278_mesh_3: THREE.Mesh;
    mesh278_mesh_4: THREE.Mesh;
    mesh278_mesh_5: THREE.Mesh;
    mesh278_mesh_6: THREE.Mesh;
    mesh278_mesh_7: THREE.Mesh;
    mesh278_mesh_8: THREE.Mesh;
    mesh287_mesh: THREE.Mesh;
    mesh287_mesh_1: THREE.Mesh;
    mesh287_mesh_2: THREE.Mesh;
    mesh287_mesh_3: THREE.Mesh;
    mesh287_mesh_4: THREE.Mesh;
    mesh287_mesh_5: THREE.Mesh;
    mesh287_mesh_6: THREE.Mesh;
    mesh287_mesh_7: THREE.Mesh;
    mesh287_mesh_8: THREE.Mesh;
    mesh296_mesh: THREE.Mesh;
    mesh296_mesh_1: THREE.Mesh;
    mesh296_mesh_2: THREE.Mesh;
    mesh296_mesh_3: THREE.Mesh;
    mesh296_mesh_4: THREE.Mesh;
    mesh301_mesh: THREE.Mesh;
    mesh301_mesh_1: THREE.Mesh;
    mesh301_mesh_2: THREE.Mesh;
    mesh301_mesh_3: THREE.Mesh;
    mesh305_mesh: THREE.Mesh;
    mesh305_mesh_1: THREE.Mesh;
    mesh305_mesh_2: THREE.Mesh;
    mesh305_mesh_3: THREE.Mesh;
    mesh305_mesh_4: THREE.Mesh;
    mesh305_mesh_5: THREE.Mesh;
    mesh305_mesh_6: THREE.Mesh;
    mesh305_mesh_7: THREE.Mesh;
    mesh305_mesh_8: THREE.Mesh;
    mesh305_mesh_9: THREE.Mesh;
    mesh305_mesh_10: THREE.Mesh;
    mesh305_mesh_11: THREE.Mesh;
    mesh305_mesh_12: THREE.Mesh;
    mesh305_mesh_13: THREE.Mesh;
    mesh305_mesh_14: THREE.Mesh;
    mesh305_mesh_15: THREE.Mesh;
    mesh305_mesh_16: THREE.Mesh;
    mesh305_mesh_17: THREE.Mesh;
    mesh305_mesh_18: THREE.Mesh;
    mesh305_mesh_19: THREE.Mesh;
    mesh305_mesh_20: THREE.Mesh;
    mesh305_mesh_21: THREE.Mesh;
    mesh305_mesh_22: THREE.Mesh;
    mesh305_mesh_23: THREE.Mesh;
    mesh305_mesh_24: THREE.Mesh;
    mesh305_mesh_25: THREE.Mesh;
    mesh305_mesh_26: THREE.Mesh;
    mesh305_mesh_27: THREE.Mesh;
    mesh305_mesh_28: THREE.Mesh;
    mesh305_mesh_29: THREE.Mesh;
    mesh305_mesh_30: THREE.Mesh;
    mesh305_mesh_31: THREE.Mesh;
    mesh305_mesh_32: THREE.Mesh;
    mesh305_mesh_33: THREE.Mesh;
    mesh305_mesh_34: THREE.Mesh;
    mesh340_mesh: THREE.Mesh;
    mesh340_mesh_1: THREE.Mesh;
    mesh340_mesh_2: THREE.Mesh;
    mesh340_mesh_3: THREE.Mesh;
    mesh340_mesh_4: THREE.Mesh;
    mesh340_mesh_5: THREE.Mesh;
    mesh340_mesh_6: THREE.Mesh;
    mesh340_mesh_7: THREE.Mesh;
    mesh340_mesh_8: THREE.Mesh;
    mesh340_mesh_9: THREE.Mesh;
    mesh340_mesh_10: THREE.Mesh;
    mesh351_mesh: THREE.Mesh;
    mesh351_mesh_1: THREE.Mesh;
    mesh351_mesh_2: THREE.Mesh;
    mesh351_mesh_3: THREE.Mesh;
    mesh351_mesh_4: THREE.Mesh;
    mesh351_mesh_5: THREE.Mesh;
    mesh351_mesh_6: THREE.Mesh;
    mesh351_mesh_7: THREE.Mesh;
    mesh351_mesh_8: THREE.Mesh;
    mesh351_mesh_9: THREE.Mesh;
    mesh351_mesh_10: THREE.Mesh;
    mesh362_mesh: THREE.Mesh;
    mesh362_mesh_1: THREE.Mesh;
    mesh362_mesh_2: THREE.Mesh;
    mesh362_mesh_3: THREE.Mesh;
    mesh362_mesh_4: THREE.Mesh;
    mesh362_mesh_5: THREE.Mesh;
    mesh362_mesh_6: THREE.Mesh;
    mesh362_mesh_7: THREE.Mesh;
    mesh362_mesh_8: THREE.Mesh;
    mesh362_mesh_9: THREE.Mesh;
    mesh362_mesh_10: THREE.Mesh;
    mesh362_mesh_11: THREE.Mesh;
    mesh362_mesh_12: THREE.Mesh;
    mesh362_mesh_13: THREE.Mesh;
    mesh362_mesh_14: THREE.Mesh;
    mesh362_mesh_15: THREE.Mesh;
    mesh362_mesh_16: THREE.Mesh;
    mesh362_mesh_17: THREE.Mesh;
    mesh362_mesh_18: THREE.Mesh;
    mesh362_mesh_19: THREE.Mesh;
    mesh362_mesh_20: THREE.Mesh;
    mesh362_mesh_21: THREE.Mesh;
    mesh362_mesh_22: THREE.Mesh;
    mesh362_mesh_23: THREE.Mesh;
    mesh362_mesh_24: THREE.Mesh;
    mesh362_mesh_25: THREE.Mesh;
    mesh362_mesh_26: THREE.Mesh;
    mesh362_mesh_27: THREE.Mesh;
    mesh362_mesh_28: THREE.Mesh;
    mesh391_mesh: THREE.Mesh;
    mesh391_mesh_1: THREE.Mesh;
    mesh391_mesh_2: THREE.Mesh;
    mesh391_mesh_3: THREE.Mesh;
    mesh391_mesh_4: THREE.Mesh;
    mesh391_mesh_5: THREE.Mesh;
    mesh397_mesh: THREE.Mesh;
    mesh397_mesh_1: THREE.Mesh;
    mesh397_mesh_2: THREE.Mesh;
    mesh397_mesh_3: THREE.Mesh;
    mesh397_mesh_4: THREE.Mesh;
    mesh397_mesh_5: THREE.Mesh;
    mesh403_mesh: THREE.Mesh;
    mesh403_mesh_1: THREE.Mesh;
    mesh403_mesh_2: THREE.Mesh;
    mesh403_mesh_3: THREE.Mesh;
    mesh403_mesh_4: THREE.Mesh;
    mesh403_mesh_5: THREE.Mesh;
    mesh409_mesh: THREE.Mesh;
    mesh409_mesh_1: THREE.Mesh;
    mesh409_mesh_2: THREE.Mesh;
    mesh409_mesh_3: THREE.Mesh;
    mesh409_mesh_4: THREE.Mesh;
    mesh409_mesh_5: THREE.Mesh;
    mesh415_mesh: THREE.Mesh;
    mesh415_mesh_1: THREE.Mesh;
    mesh415_mesh_2: THREE.Mesh;
    mesh415_mesh_3: THREE.Mesh;
    mesh415_mesh_4: THREE.Mesh;
    mesh415_mesh_5: THREE.Mesh;
    mesh415_mesh_6: THREE.Mesh;
    mesh415_mesh_7: THREE.Mesh;
    mesh423_mesh: THREE.Mesh;
    mesh423_mesh_1: THREE.Mesh;
    mesh423_mesh_2: THREE.Mesh;
    mesh423_mesh_3: THREE.Mesh;
    mesh423_mesh_4: THREE.Mesh;
    mesh423_mesh_5: THREE.Mesh;
    mesh423_mesh_6: THREE.Mesh;
    mesh423_mesh_7: THREE.Mesh;
    mesh431_mesh: THREE.Mesh;
    mesh431_mesh_1: THREE.Mesh;
    mesh431_mesh_2: THREE.Mesh;
    mesh431_mesh_3: THREE.Mesh;
    mesh435_mesh: THREE.Mesh;
    mesh435_mesh_1: THREE.Mesh;
    mesh435_mesh_2: THREE.Mesh;
    mesh435_mesh_3: THREE.Mesh;
    mesh435_mesh_4: THREE.Mesh;
    mesh435_mesh_5: THREE.Mesh;
    mesh441_mesh: THREE.Mesh;
    mesh441_mesh_1: THREE.Mesh;
    mesh441_mesh_2: THREE.Mesh;
    mesh441_mesh_3: THREE.Mesh;
    mesh441_mesh_4: THREE.Mesh;
    mesh441_mesh_5: THREE.Mesh;
    mesh441_mesh_6: THREE.Mesh;
  };
  materials: {
    ["0.301961_0.290196_0.262745_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.105882_0.372549_0.666667_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.811765_0.858824_0.898039_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.376471_0.415686_0.450980_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.850980_0.756863_0.866667_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.564706_0.811765_0.945098_0.000000_0.000000"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/hovercraft_mk6.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_1.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_2.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_3.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_4.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_5.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_6.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_7.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_8.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_9.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_10.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_11.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_12.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_13.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_14.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_15.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_16.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_17.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_18.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_19.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_20.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_21.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_22.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_23.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_24.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_25.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_26.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_27.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_28.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_29.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_30.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_31.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_32.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_33.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_34.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_35.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_36.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_37.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_38.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_39.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_40.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_41.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_42.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_43.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_44.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_45.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_46.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_47.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_48.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_49.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_50.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_51.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_52.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_53.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_54.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_55.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_56.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_57.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_58.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_59.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_60.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_61.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_62.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_63.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_64.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_65.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_66.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_67.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_68.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_69.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_70.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_71.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_72.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_73.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_74.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_75.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_76.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_77.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_78.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_79.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_80.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_81.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_82.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_83.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_84.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_85.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_86.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_87.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_88.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_89.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_90.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_91.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_92.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_93.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_94.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_95.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_96.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_97.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_98.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_99.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_100.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_101.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_102.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_103.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_104.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_105.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_106.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_107.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_108.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_109.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_110.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_111.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_112.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_113.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_114.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_115.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_116.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_117.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_118.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_119.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_120.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_121.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_122.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_123.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_124.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_125.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_126.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_127.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_128.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_129.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_130.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_131.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_132.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_133.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_134.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_135.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_136.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_137.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_138.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_139.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_140.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_141.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_142.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_143.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_144.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_145.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_146.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_147.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_148.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_149.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_150.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_151.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_152.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_153.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_154.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_155.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_156.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_157.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_158.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_159.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_160.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_161.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_162.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_163.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_164.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_165.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_166.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_167.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_168.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_169.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_170.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_171.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_172.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_173.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_174.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_175.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_176.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_177.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_178.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_179.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_180.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_181.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_182.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_183.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_184.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_185.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_186.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_187.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_188.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_189.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_190.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_191.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_192.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_193.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_194.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_195.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_196.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_197.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_198.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_199.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_200.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_201.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_202.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_203.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_204.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_205.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_206.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_207.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_208.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_209.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_210.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_211.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_212.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_213.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_214.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_215.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_216.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_217.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_218.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_219.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_220.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_221.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_222.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_223.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_224.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_225.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_226.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_227.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_228.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_229.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_230.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_231.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_232.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_233.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_234.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_235.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_236.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_237.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_238.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_239.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_240.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_241.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_242.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_243.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_244.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_245.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_246.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_247.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_248.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_249.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_250.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_251.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_252.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_253.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_254.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_255.geometry}
        material={materials["0.301961_0.290196_0.262745_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256_mesh.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256_mesh_1.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256_mesh_2.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256_mesh_3.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256_mesh_4.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256_mesh_5.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh262_mesh_6.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_1.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_2.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_3.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_4.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_5.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_6.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_7.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh269_mesh_8.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_1.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_2.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_3.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_4.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_5.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_6.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_7.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh278_mesh_8.geometry}
        material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_1.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_2.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_3.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_4.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_5.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_6.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_7.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh287_mesh_8.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh296_mesh.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh296_mesh_1.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh296_mesh_2.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh296_mesh_3.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh296_mesh_4.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh301_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh301_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh301_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh301_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_1.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_2.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_3.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_4.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_5.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_6.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_7.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_8.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_9.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_10.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_11.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_12.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_13.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_14.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_15.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_16.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_17.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_18.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_19.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_20.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_21.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_22.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_23.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_24.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_25.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_26.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_27.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_28.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_29.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_30.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_31.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_32.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_33.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_34.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_1.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_2.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_3.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_4.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_5.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_6.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_7.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_8.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_9.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh340_mesh_10.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_1.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_2.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_3.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_4.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_5.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_6.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_7.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_8.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_9.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh351_mesh_10.geometry}
        material={materials["0.564706_0.811765_0.945098_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_1.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_2.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_3.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_4.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_5.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_6.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_7.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_8.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_9.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_10.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_11.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_12.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_13.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_14.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_15.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_16.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_17.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_18.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_19.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_20.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_21.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_22.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_23.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_24.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_25.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_26.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_27.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh362_mesh_28.geometry}
        material={materials["0.105882_0.372549_0.666667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh391_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh391_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh391_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh391_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh391_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh391_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh397_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh397_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh397_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh397_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh397_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh397_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh403_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh403_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh403_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh403_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh403_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh403_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh409_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh409_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh409_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh409_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh409_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh409_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_6.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh415_mesh_7.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_6.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh423_mesh_7.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh431_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh431_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh431_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh431_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh435_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh435_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh435_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh435_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh435_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh435_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh_1.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh_2.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh_3.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh_4.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh_5.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh441_mesh_6.geometry}
        material={materials["0.811765_0.858824_0.898039_0.000000_0.000000"]}
      />
    </group>
  );
}

useGLTF.preload("/models/hovercraft_mk6.gltf");

export const Scene: React.FC = () => {
  return (
    <SceneWrapper>
      <Model />
    </SceneWrapper>
  );
};
