/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/hovercraft_mk8.gltf -t -r models -s -o src/components/models/hovercraft-mk8.tsx 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh0_mesh: THREE.Mesh;
    mesh0_mesh_1: THREE.Mesh;
    mesh0_mesh_2: THREE.Mesh;
    mesh0_mesh_3: THREE.Mesh;
    mesh0_mesh_4: THREE.Mesh;
    mesh0_mesh_5: THREE.Mesh;
    mesh0_mesh_6: THREE.Mesh;
    mesh0_mesh_7: THREE.Mesh;
    mesh0_mesh_8: THREE.Mesh;
    mesh0_mesh_9: THREE.Mesh;
    mesh0_mesh_10: THREE.Mesh;
    mesh0_mesh_11: THREE.Mesh;
    mesh0_mesh_12: THREE.Mesh;
    mesh0_mesh_13: THREE.Mesh;
    mesh0_mesh_14: THREE.Mesh;
    mesh0_mesh_15: THREE.Mesh;
    mesh0_mesh_16: THREE.Mesh;
    mesh0_mesh_17: THREE.Mesh;
    mesh0_mesh_18: THREE.Mesh;
    mesh0_mesh_19: THREE.Mesh;
    mesh0_mesh_20: THREE.Mesh;
    mesh0_mesh_21: THREE.Mesh;
    mesh0_mesh_22: THREE.Mesh;
    mesh0_mesh_23: THREE.Mesh;
    mesh0_mesh_24: THREE.Mesh;
    mesh0_mesh_25: THREE.Mesh;
    mesh0_mesh_26: THREE.Mesh;
    mesh0_mesh_27: THREE.Mesh;
    mesh0_mesh_28: THREE.Mesh;
    mesh0_mesh_29: THREE.Mesh;
    mesh0_mesh_30: THREE.Mesh;
    mesh0_mesh_31: THREE.Mesh;
    mesh0_mesh_32: THREE.Mesh;
    mesh0_mesh_33: THREE.Mesh;
    mesh34_mesh: THREE.Mesh;
    mesh34_mesh_1: THREE.Mesh;
    mesh34_mesh_2: THREE.Mesh;
    mesh34_mesh_3: THREE.Mesh;
    mesh34_mesh_4: THREE.Mesh;
    mesh34_mesh_5: THREE.Mesh;
    mesh34_mesh_6: THREE.Mesh;
    mesh34_mesh_7: THREE.Mesh;
    mesh34_mesh_8: THREE.Mesh;
    mesh34_mesh_9: THREE.Mesh;
    mesh34_mesh_10: THREE.Mesh;
    mesh34_mesh_11: THREE.Mesh;
    mesh34_mesh_12: THREE.Mesh;
    mesh34_mesh_13: THREE.Mesh;
    mesh34_mesh_14: THREE.Mesh;
    mesh34_mesh_15: THREE.Mesh;
    mesh34_mesh_16: THREE.Mesh;
    mesh34_mesh_17: THREE.Mesh;
    mesh34_mesh_18: THREE.Mesh;
    mesh34_mesh_19: THREE.Mesh;
    mesh34_mesh_20: THREE.Mesh;
    mesh34_mesh_21: THREE.Mesh;
    mesh34_mesh_22: THREE.Mesh;
    mesh57_mesh: THREE.Mesh;
    mesh57_mesh_1: THREE.Mesh;
    mesh57_mesh_2: THREE.Mesh;
    mesh57_mesh_3: THREE.Mesh;
    mesh57_mesh_4: THREE.Mesh;
    mesh57_mesh_5: THREE.Mesh;
    mesh57_mesh_6: THREE.Mesh;
    mesh64_mesh: THREE.Mesh;
    mesh64_mesh_1: THREE.Mesh;
    mesh64_mesh_2: THREE.Mesh;
    mesh64_mesh_3: THREE.Mesh;
    mesh64_mesh_4: THREE.Mesh;
    mesh64_mesh_5: THREE.Mesh;
    mesh64_mesh_6: THREE.Mesh;
    mesh64_mesh_7: THREE.Mesh;
    mesh64_mesh_8: THREE.Mesh;
    mesh64_mesh_9: THREE.Mesh;
    mesh64_mesh_10: THREE.Mesh;
    mesh64_mesh_11: THREE.Mesh;
    mesh64_mesh_12: THREE.Mesh;
    mesh64_mesh_13: THREE.Mesh;
    mesh64_mesh_14: THREE.Mesh;
    mesh64_mesh_15: THREE.Mesh;
    mesh64_mesh_16: THREE.Mesh;
    mesh64_mesh_17: THREE.Mesh;
    mesh64_mesh_18: THREE.Mesh;
    mesh64_mesh_19: THREE.Mesh;
    mesh64_mesh_20: THREE.Mesh;
    mesh64_mesh_21: THREE.Mesh;
    mesh64_mesh_22: THREE.Mesh;
    mesh87_mesh: THREE.Mesh;
    mesh87_mesh_1: THREE.Mesh;
    mesh87_mesh_2: THREE.Mesh;
    mesh87_mesh_3: THREE.Mesh;
    mesh87_mesh_4: THREE.Mesh;
    mesh87_mesh_5: THREE.Mesh;
    mesh87_mesh_6: THREE.Mesh;
    mesh87_mesh_7: THREE.Mesh;
    mesh87_mesh_8: THREE.Mesh;
    mesh87_mesh_9: THREE.Mesh;
    mesh87_mesh_10: THREE.Mesh;
    mesh87_mesh_11: THREE.Mesh;
    mesh87_mesh_12: THREE.Mesh;
    mesh87_mesh_13: THREE.Mesh;
    mesh87_mesh_14: THREE.Mesh;
    mesh102_mesh: THREE.Mesh;
    mesh102_mesh_1: THREE.Mesh;
    mesh102_mesh_2: THREE.Mesh;
    mesh102_mesh_3: THREE.Mesh;
    mesh106_mesh: THREE.Mesh;
    mesh106_mesh_1: THREE.Mesh;
    mesh106_mesh_2: THREE.Mesh;
    mesh106_mesh_3: THREE.Mesh;
    mesh106_mesh_4: THREE.Mesh;
    mesh106_mesh_5: THREE.Mesh;
    mesh106_mesh_6: THREE.Mesh;
    mesh106_mesh_7: THREE.Mesh;
    mesh106_mesh_8: THREE.Mesh;
    mesh106_mesh_9: THREE.Mesh;
    mesh106_mesh_10: THREE.Mesh;
    mesh106_mesh_11: THREE.Mesh;
    mesh106_mesh_12: THREE.Mesh;
    mesh106_mesh_13: THREE.Mesh;
    mesh106_mesh_14: THREE.Mesh;
    mesh106_mesh_15: THREE.Mesh;
    mesh106_mesh_16: THREE.Mesh;
    mesh106_mesh_17: THREE.Mesh;
    mesh106_mesh_18: THREE.Mesh;
    mesh106_mesh_19: THREE.Mesh;
    mesh106_mesh_20: THREE.Mesh;
    mesh106_mesh_21: THREE.Mesh;
    mesh106_mesh_22: THREE.Mesh;
    mesh106_mesh_23: THREE.Mesh;
    mesh106_mesh_24: THREE.Mesh;
    mesh106_mesh_25: THREE.Mesh;
    mesh106_mesh_26: THREE.Mesh;
    mesh106_mesh_27: THREE.Mesh;
    mesh106_mesh_28: THREE.Mesh;
    mesh106_mesh_29: THREE.Mesh;
    mesh106_mesh_30: THREE.Mesh;
    mesh106_mesh_31: THREE.Mesh;
    mesh106_mesh_32: THREE.Mesh;
    mesh106_mesh_33: THREE.Mesh;
    mesh140_mesh: THREE.Mesh;
    mesh140_mesh_1: THREE.Mesh;
    mesh140_mesh_2: THREE.Mesh;
    mesh140_mesh_3: THREE.Mesh;
    mesh140_mesh_4: THREE.Mesh;
    mesh140_mesh_5: THREE.Mesh;
    mesh140_mesh_6: THREE.Mesh;
    mesh140_mesh_7: THREE.Mesh;
    mesh140_mesh_8: THREE.Mesh;
    mesh140_mesh_9: THREE.Mesh;
    mesh140_mesh_10: THREE.Mesh;
    mesh140_mesh_11: THREE.Mesh;
    mesh140_mesh_12: THREE.Mesh;
    mesh140_mesh_13: THREE.Mesh;
    mesh140_mesh_14: THREE.Mesh;
    mesh140_mesh_15: THREE.Mesh;
    mesh140_mesh_16: THREE.Mesh;
    mesh140_mesh_17: THREE.Mesh;
    mesh140_mesh_18: THREE.Mesh;
    mesh140_mesh_19: THREE.Mesh;
    mesh140_mesh_20: THREE.Mesh;
    mesh140_mesh_21: THREE.Mesh;
    mesh140_mesh_22: THREE.Mesh;
    mesh163_mesh: THREE.Mesh;
    mesh163_mesh_1: THREE.Mesh;
    mesh163_mesh_2: THREE.Mesh;
    mesh163_mesh_3: THREE.Mesh;
    mesh163_mesh_4: THREE.Mesh;
    mesh163_mesh_5: THREE.Mesh;
    mesh163_mesh_6: THREE.Mesh;
    mesh170_mesh: THREE.Mesh;
    mesh170_mesh_1: THREE.Mesh;
    mesh170_mesh_2: THREE.Mesh;
    mesh170_mesh_3: THREE.Mesh;
    mesh170_mesh_4: THREE.Mesh;
    mesh170_mesh_5: THREE.Mesh;
    mesh170_mesh_6: THREE.Mesh;
    mesh170_mesh_7: THREE.Mesh;
    mesh170_mesh_8: THREE.Mesh;
    mesh170_mesh_9: THREE.Mesh;
    mesh170_mesh_10: THREE.Mesh;
    mesh170_mesh_11: THREE.Mesh;
    mesh170_mesh_12: THREE.Mesh;
    mesh170_mesh_13: THREE.Mesh;
    mesh170_mesh_14: THREE.Mesh;
    mesh170_mesh_15: THREE.Mesh;
    mesh170_mesh_16: THREE.Mesh;
    mesh170_mesh_17: THREE.Mesh;
    mesh170_mesh_18: THREE.Mesh;
    mesh170_mesh_19: THREE.Mesh;
    mesh170_mesh_20: THREE.Mesh;
    mesh170_mesh_21: THREE.Mesh;
    mesh170_mesh_22: THREE.Mesh;
    mesh193_mesh: THREE.Mesh;
    mesh193_mesh_1: THREE.Mesh;
    mesh193_mesh_2: THREE.Mesh;
    mesh193_mesh_3: THREE.Mesh;
    mesh193_mesh_4: THREE.Mesh;
    mesh193_mesh_5: THREE.Mesh;
    mesh193_mesh_6: THREE.Mesh;
    mesh193_mesh_7: THREE.Mesh;
    mesh193_mesh_8: THREE.Mesh;
    mesh193_mesh_9: THREE.Mesh;
    mesh193_mesh_10: THREE.Mesh;
    mesh193_mesh_11: THREE.Mesh;
    mesh193_mesh_12: THREE.Mesh;
    mesh193_mesh_13: THREE.Mesh;
    mesh193_mesh_14: THREE.Mesh;
    mesh208_mesh: THREE.Mesh;
    mesh208_mesh_1: THREE.Mesh;
    mesh208_mesh_2: THREE.Mesh;
    mesh208_mesh_3: THREE.Mesh;
    mesh212_mesh: THREE.Mesh;
    mesh212_mesh_1: THREE.Mesh;
    mesh212_mesh_2: THREE.Mesh;
    mesh212_mesh_3: THREE.Mesh;
    mesh212_mesh_4: THREE.Mesh;
    mesh212_mesh_5: THREE.Mesh;
    mesh212_mesh_6: THREE.Mesh;
    mesh212_mesh_7: THREE.Mesh;
    mesh212_mesh_8: THREE.Mesh;
    mesh212_mesh_9: THREE.Mesh;
    mesh212_mesh_10: THREE.Mesh;
    mesh212_mesh_11: THREE.Mesh;
    mesh212_mesh_12: THREE.Mesh;
    mesh212_mesh_13: THREE.Mesh;
    mesh212_mesh_14: THREE.Mesh;
    mesh212_mesh_15: THREE.Mesh;
    mesh212_mesh_16: THREE.Mesh;
    mesh212_mesh_17: THREE.Mesh;
    mesh212_mesh_18: THREE.Mesh;
    mesh212_mesh_19: THREE.Mesh;
    mesh212_mesh_20: THREE.Mesh;
    mesh212_mesh_21: THREE.Mesh;
    mesh212_mesh_22: THREE.Mesh;
    mesh235_mesh: THREE.Mesh;
    mesh235_mesh_1: THREE.Mesh;
    mesh235_mesh_2: THREE.Mesh;
    mesh235_mesh_3: THREE.Mesh;
    mesh235_mesh_4: THREE.Mesh;
    mesh235_mesh_5: THREE.Mesh;
    mesh235_mesh_6: THREE.Mesh;
    mesh242_mesh: THREE.Mesh;
    mesh242_mesh_1: THREE.Mesh;
    mesh242_mesh_2: THREE.Mesh;
    mesh242_mesh_3: THREE.Mesh;
    mesh242_mesh_4: THREE.Mesh;
    mesh242_mesh_5: THREE.Mesh;
    mesh242_mesh_6: THREE.Mesh;
    mesh249_mesh: THREE.Mesh;
    mesh249_mesh_1: THREE.Mesh;
    mesh249_mesh_2: THREE.Mesh;
    mesh249_mesh_3: THREE.Mesh;
    mesh249_mesh_4: THREE.Mesh;
    mesh249_mesh_5: THREE.Mesh;
    mesh249_mesh_6: THREE.Mesh;
    mesh249_mesh_7: THREE.Mesh;
    mesh249_mesh_8: THREE.Mesh;
    mesh249_mesh_9: THREE.Mesh;
    mesh249_mesh_10: THREE.Mesh;
    mesh249_mesh_11: THREE.Mesh;
    mesh249_mesh_12: THREE.Mesh;
    mesh249_mesh_13: THREE.Mesh;
    mesh249_mesh_14: THREE.Mesh;
    mesh249_mesh_15: THREE.Mesh;
    mesh249_mesh_16: THREE.Mesh;
    mesh249_mesh_17: THREE.Mesh;
    mesh249_mesh_18: THREE.Mesh;
    mesh268_mesh: THREE.Mesh;
    mesh268_mesh_1: THREE.Mesh;
    mesh268_mesh_2: THREE.Mesh;
    mesh268_mesh_3: THREE.Mesh;
    mesh268_mesh_4: THREE.Mesh;
    mesh268_mesh_5: THREE.Mesh;
    mesh268_mesh_6: THREE.Mesh;
    mesh275_mesh: THREE.Mesh;
    mesh275_mesh_1: THREE.Mesh;
    mesh275_mesh_2: THREE.Mesh;
    mesh275_mesh_3: THREE.Mesh;
    mesh275_mesh_4: THREE.Mesh;
    mesh275_mesh_5: THREE.Mesh;
    mesh275_mesh_6: THREE.Mesh;
    mesh282_mesh: THREE.Mesh;
    mesh282_mesh_1: THREE.Mesh;
    mesh282_mesh_2: THREE.Mesh;
    mesh282_mesh_3: THREE.Mesh;
    mesh282_mesh_4: THREE.Mesh;
    mesh282_mesh_5: THREE.Mesh;
    mesh282_mesh_6: THREE.Mesh;
    mesh289_mesh: THREE.Mesh;
    mesh289_mesh_1: THREE.Mesh;
    mesh289_mesh_2: THREE.Mesh;
    mesh289_mesh_3: THREE.Mesh;
    mesh289_mesh_4: THREE.Mesh;
    mesh289_mesh_5: THREE.Mesh;
    mesh289_mesh_6: THREE.Mesh;
    mesh289_mesh_7: THREE.Mesh;
    mesh289_mesh_8: THREE.Mesh;
    mesh289_mesh_9: THREE.Mesh;
    mesh299_mesh: THREE.Mesh;
    mesh299_mesh_1: THREE.Mesh;
    mesh299_mesh_2: THREE.Mesh;
    mesh299_mesh_3: THREE.Mesh;
    mesh299_mesh_4: THREE.Mesh;
    mesh299_mesh_5: THREE.Mesh;
    mesh305_mesh: THREE.Mesh;
    mesh305_mesh_1: THREE.Mesh;
    mesh305_mesh_2: THREE.Mesh;
    mesh305_mesh_3: THREE.Mesh;
    mesh305_mesh_4: THREE.Mesh;
    mesh305_mesh_5: THREE.Mesh;
    mesh305_mesh_6: THREE.Mesh;
    mesh305_mesh_7: THREE.Mesh;
    mesh305_mesh_8: THREE.Mesh;
    mesh305_mesh_9: THREE.Mesh;
    mesh305_mesh_10: THREE.Mesh;
    mesh316_mesh: THREE.Mesh;
    mesh316_mesh_1: THREE.Mesh;
    mesh316_mesh_2: THREE.Mesh;
    mesh316_mesh_3: THREE.Mesh;
    mesh316_mesh_4: THREE.Mesh;
    mesh316_mesh_5: THREE.Mesh;
    mesh316_mesh_6: THREE.Mesh;
    mesh316_mesh_7: THREE.Mesh;
    mesh316_mesh_8: THREE.Mesh;
    mesh316_mesh_9: THREE.Mesh;
    mesh326_mesh: THREE.Mesh;
    mesh326_mesh_1: THREE.Mesh;
    mesh326_mesh_2: THREE.Mesh;
    mesh326_mesh_3: THREE.Mesh;
    mesh326_mesh_4: THREE.Mesh;
    mesh326_mesh_5: THREE.Mesh;
    mesh326_mesh_6: THREE.Mesh;
    mesh326_mesh_7: THREE.Mesh;
    mesh326_mesh_8: THREE.Mesh;
    mesh326_mesh_9: THREE.Mesh;
    mesh336_mesh: THREE.Mesh;
    mesh336_mesh_1: THREE.Mesh;
    mesh336_mesh_2: THREE.Mesh;
    mesh336_mesh_3: THREE.Mesh;
    mesh336_mesh_4: THREE.Mesh;
    mesh336_mesh_5: THREE.Mesh;
    mesh336_mesh_6: THREE.Mesh;
    mesh336_mesh_7: THREE.Mesh;
    mesh336_mesh_8: THREE.Mesh;
    mesh336_mesh_9: THREE.Mesh;
    mesh346_mesh: THREE.Mesh;
    mesh346_mesh_1: THREE.Mesh;
    mesh346_mesh_2: THREE.Mesh;
    mesh346_mesh_3: THREE.Mesh;
    mesh346_mesh_4: THREE.Mesh;
    mesh346_mesh_5: THREE.Mesh;
    mesh346_mesh_6: THREE.Mesh;
    mesh346_mesh_7: THREE.Mesh;
    mesh346_mesh_8: THREE.Mesh;
    mesh346_mesh_9: THREE.Mesh;
    mesh346_mesh_10: THREE.Mesh;
    mesh346_mesh_11: THREE.Mesh;
    mesh346_mesh_12: THREE.Mesh;
    mesh346_mesh_13: THREE.Mesh;
    mesh346_mesh_14: THREE.Mesh;
    mesh346_mesh_15: THREE.Mesh;
    mesh346_mesh_16: THREE.Mesh;
    mesh346_mesh_17: THREE.Mesh;
    mesh346_mesh_18: THREE.Mesh;
    mesh346_mesh_19: THREE.Mesh;
    mesh346_mesh_20: THREE.Mesh;
    mesh346_mesh_21: THREE.Mesh;
    mesh346_mesh_22: THREE.Mesh;
    mesh346_mesh_23: THREE.Mesh;
    mesh346_mesh_24: THREE.Mesh;
    mesh346_mesh_25: THREE.Mesh;
    mesh346_mesh_26: THREE.Mesh;
    mesh346_mesh_27: THREE.Mesh;
    mesh346_mesh_28: THREE.Mesh;
    mesh346_mesh_29: THREE.Mesh;
    mesh346_mesh_30: THREE.Mesh;
    mesh346_mesh_31: THREE.Mesh;
    mesh346_mesh_32: THREE.Mesh;
    mesh346_mesh_33: THREE.Mesh;
    mesh346_mesh_34: THREE.Mesh;
    mesh346_mesh_35: THREE.Mesh;
    mesh346_mesh_36: THREE.Mesh;
    mesh346_mesh_37: THREE.Mesh;
    mesh346_mesh_38: THREE.Mesh;
    mesh346_mesh_39: THREE.Mesh;
    mesh346_mesh_40: THREE.Mesh;
    mesh346_mesh_41: THREE.Mesh;
    mesh346_mesh_42: THREE.Mesh;
    mesh346_mesh_43: THREE.Mesh;
    mesh346_mesh_44: THREE.Mesh;
    mesh346_mesh_45: THREE.Mesh;
    mesh346_mesh_46: THREE.Mesh;
    mesh346_mesh_47: THREE.Mesh;
    mesh346_mesh_48: THREE.Mesh;
    mesh346_mesh_49: THREE.Mesh;
    mesh346_mesh_50: THREE.Mesh;
    mesh346_mesh_51: THREE.Mesh;
    mesh346_mesh_52: THREE.Mesh;
    mesh346_mesh_53: THREE.Mesh;
    mesh346_mesh_54: THREE.Mesh;
    mesh346_mesh_55: THREE.Mesh;
    mesh346_mesh_56: THREE.Mesh;
    mesh346_mesh_57: THREE.Mesh;
    mesh346_mesh_58: THREE.Mesh;
    mesh346_mesh_59: THREE.Mesh;
    mesh346_mesh_60: THREE.Mesh;
    mesh407_mesh: THREE.Mesh;
    mesh407_mesh_1: THREE.Mesh;
    mesh407_mesh_2: THREE.Mesh;
    mesh407_mesh_3: THREE.Mesh;
    mesh407_mesh_4: THREE.Mesh;
    mesh412_mesh: THREE.Mesh;
    mesh412_mesh_1: THREE.Mesh;
    mesh412_mesh_2: THREE.Mesh;
    mesh412_mesh_3: THREE.Mesh;
    mesh412_mesh_4: THREE.Mesh;
    mesh417_mesh: THREE.Mesh;
    mesh417_mesh_1: THREE.Mesh;
    mesh417_mesh_2: THREE.Mesh;
    mesh417_mesh_3: THREE.Mesh;
    mesh417_mesh_4: THREE.Mesh;
    mesh417_mesh_5: THREE.Mesh;
    mesh417_mesh_6: THREE.Mesh;
    mesh417_mesh_7: THREE.Mesh;
    mesh417_mesh_8: THREE.Mesh;
    mesh417_mesh_9: THREE.Mesh;
    mesh417_mesh_10: THREE.Mesh;
    mesh417_mesh_11: THREE.Mesh;
    mesh417_mesh_12: THREE.Mesh;
    mesh417_mesh_13: THREE.Mesh;
    mesh417_mesh_14: THREE.Mesh;
    mesh417_mesh_15: THREE.Mesh;
    mesh417_mesh_16: THREE.Mesh;
    mesh417_mesh_17: THREE.Mesh;
    mesh417_mesh_18: THREE.Mesh;
    mesh436_mesh: THREE.Mesh;
    mesh436_mesh_1: THREE.Mesh;
    mesh436_mesh_2: THREE.Mesh;
    mesh436_mesh_3: THREE.Mesh;
    mesh436_mesh_4: THREE.Mesh;
    mesh436_mesh_5: THREE.Mesh;
    mesh442_mesh: THREE.Mesh;
    mesh442_mesh_1: THREE.Mesh;
    mesh442_mesh_2: THREE.Mesh;
    mesh442_mesh_3: THREE.Mesh;
    mesh442_mesh_4: THREE.Mesh;
    mesh442_mesh_5: THREE.Mesh;
  };
  materials: {
    ["0.262745_0.282353_0.301961_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.760784_0.839216_0.925490_0.000000_0.400000"]: THREE.MeshStandardMaterial;
    ["0.752941_0.619608_0.439216_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.901961_0.901961_0.901961_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.850980_0.756863_0.866667_0.000000_0.000000"]: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/../public/models/hovercraft_mk8.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_19.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_20.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_21.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_22.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_23.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_24.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_25.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_26.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_27.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_28.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_29.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_30.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_31.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_32.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_33.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_19.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_20.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_21.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh34_mesh_22.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh57_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_19.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_20.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_21.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh64_mesh_22.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh87_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh102_mesh.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh102_mesh_1.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh102_mesh_2.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh102_mesh_3.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_19.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_20.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_21.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_22.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_23.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_24.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_25.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_26.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_27.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_28.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_29.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_30.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_31.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_32.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh106_mesh_33.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_19.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_20.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_21.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh140_mesh_22.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh163_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_19.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_20.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_21.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh170_mesh_22.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh193_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh208_mesh.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh208_mesh_1.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh208_mesh_2.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh208_mesh_3.geometry}
        material={materials["0.760784_0.839216_0.925490_0.000000_0.400000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_1.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_2.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_3.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_4.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_5.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_6.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_7.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_8.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_9.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_10.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_11.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_12.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_13.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_14.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_15.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_16.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_17.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_18.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_19.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_20.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_21.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh212_mesh_22.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh235_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh242_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_7.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_8.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_9.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_10.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_11.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_12.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_13.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_14.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_15.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_16.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_17.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh249_mesh_18.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh268_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh275_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh282_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_1.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_2.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_3.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_4.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_5.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_6.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_7.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_8.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh289_mesh_9.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh299_mesh.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh299_mesh_1.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh299_mesh_2.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh299_mesh_3.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh299_mesh_4.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh299_mesh_5.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_1.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_2.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_3.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_4.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_5.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_6.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_7.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_8.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_9.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh305_mesh_10.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_7.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_8.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh316_mesh_9.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_7.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_8.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh326_mesh_9.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_7.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_8.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh336_mesh_9.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_6.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_7.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_8.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_9.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_10.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_11.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_12.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_13.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_14.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_15.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_16.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_17.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_18.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_19.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_20.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_21.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_22.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_23.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_24.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_25.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_26.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_27.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_28.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_29.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_30.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_31.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_32.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_33.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_34.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_35.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_36.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_37.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_38.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_39.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_40.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_41.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_42.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_43.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_44.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_45.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_46.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_47.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_48.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_49.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_50.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_51.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_52.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_53.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_54.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_55.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_56.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_57.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_58.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_59.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh346_mesh_60.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh407_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh407_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh407_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh407_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh407_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh412_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh412_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh412_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh412_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh412_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_1.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_2.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_3.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_4.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_5.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_6.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_7.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_8.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_9.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_10.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_11.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_12.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_13.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_14.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_15.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_16.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_17.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh417_mesh_18.geometry}
        material={materials["0.262745_0.282353_0.301961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh436_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh436_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh436_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh436_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh436_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh436_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh442_mesh.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh442_mesh_1.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh442_mesh_2.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh442_mesh_3.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh442_mesh_4.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh442_mesh_5.geometry}
        material={materials["0.901961_0.901961_0.901961_0.000000_0.000000"]}
      />
    </group>
  );
}

useGLTF.preload("/../public/models/hovercraft_mk8.gltf");
