/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh0_mesh: THREE.Mesh;
    mesh0_mesh_1: THREE.Mesh;
    mesh0_mesh_2: THREE.Mesh;
    mesh3_mesh: THREE.Mesh;
    mesh3_mesh_1: THREE.Mesh;
    mesh3_mesh_2: THREE.Mesh;
    mesh3_mesh_3: THREE.Mesh;
    mesh3_mesh_4: THREE.Mesh;
    mesh3_mesh_5: THREE.Mesh;
    mesh3_mesh_6: THREE.Mesh;
    mesh3_mesh_7: THREE.Mesh;
    mesh3_mesh_8: THREE.Mesh;
    mesh3_mesh_9: THREE.Mesh;
    mesh3_mesh_10: THREE.Mesh;
    mesh3_mesh_11: THREE.Mesh;
    mesh3_mesh_12: THREE.Mesh;
    mesh16_mesh: THREE.Mesh;
    mesh16_mesh_1: THREE.Mesh;
    mesh16_mesh_2: THREE.Mesh;
    mesh16_mesh_3: THREE.Mesh;
    mesh16_mesh_4: THREE.Mesh;
    mesh16_mesh_5: THREE.Mesh;
    mesh22_mesh: THREE.Mesh;
    mesh22_mesh_1: THREE.Mesh;
    mesh22_mesh_2: THREE.Mesh;
    mesh22_mesh_3: THREE.Mesh;
    mesh22_mesh_4: THREE.Mesh;
    mesh22_mesh_5: THREE.Mesh;
    mesh22_mesh_6: THREE.Mesh;
    mesh22_mesh_7: THREE.Mesh;
    mesh22_mesh_8: THREE.Mesh;
    mesh22_mesh_9: THREE.Mesh;
    mesh22_mesh_10: THREE.Mesh;
    mesh22_mesh_11: THREE.Mesh;
    mesh22_mesh_12: THREE.Mesh;
    mesh22_mesh_13: THREE.Mesh;
    mesh22_mesh_14: THREE.Mesh;
    mesh22_mesh_15: THREE.Mesh;
    mesh22_mesh_16: THREE.Mesh;
    mesh22_mesh_17: THREE.Mesh;
    mesh22_mesh_18: THREE.Mesh;
    mesh22_mesh_19: THREE.Mesh;
    mesh22_mesh_20: THREE.Mesh;
    mesh22_mesh_21: THREE.Mesh;
    mesh22_mesh_22: THREE.Mesh;
    mesh22_mesh_23: THREE.Mesh;
    mesh22_mesh_24: THREE.Mesh;
    mesh22_mesh_25: THREE.Mesh;
    mesh22_mesh_26: THREE.Mesh;
    mesh22_mesh_27: THREE.Mesh;
    mesh22_mesh_28: THREE.Mesh;
    mesh22_mesh_29: THREE.Mesh;
    mesh52_mesh: THREE.Mesh;
    mesh52_mesh_1: THREE.Mesh;
    mesh52_mesh_2: THREE.Mesh;
    mesh52_mesh_3: THREE.Mesh;
    mesh52_mesh_4: THREE.Mesh;
    mesh52_mesh_5: THREE.Mesh;
    mesh58_mesh: THREE.Mesh;
    mesh58_mesh_1: THREE.Mesh;
    mesh58_mesh_2: THREE.Mesh;
    mesh58_mesh_3: THREE.Mesh;
    mesh58_mesh_4: THREE.Mesh;
    mesh58_mesh_5: THREE.Mesh;
    mesh58_mesh_6: THREE.Mesh;
    mesh58_mesh_7: THREE.Mesh;
    mesh58_mesh_8: THREE.Mesh;
    mesh58_mesh_9: THREE.Mesh;
    mesh58_mesh_10: THREE.Mesh;
    mesh58_mesh_11: THREE.Mesh;
    mesh58_mesh_12: THREE.Mesh;
    mesh58_mesh_13: THREE.Mesh;
    mesh58_mesh_14: THREE.Mesh;
    mesh58_mesh_15: THREE.Mesh;
    mesh58_mesh_16: THREE.Mesh;
    mesh58_mesh_17: THREE.Mesh;
    mesh58_mesh_18: THREE.Mesh;
    mesh58_mesh_19: THREE.Mesh;
    mesh58_mesh_20: THREE.Mesh;
    mesh58_mesh_21: THREE.Mesh;
    mesh58_mesh_22: THREE.Mesh;
    mesh58_mesh_23: THREE.Mesh;
    mesh58_mesh_24: THREE.Mesh;
    mesh58_mesh_25: THREE.Mesh;
    mesh58_mesh_26: THREE.Mesh;
    mesh58_mesh_27: THREE.Mesh;
    mesh58_mesh_28: THREE.Mesh;
    mesh58_mesh_29: THREE.Mesh;
    mesh58_mesh_30: THREE.Mesh;
    mesh58_mesh_31: THREE.Mesh;
    mesh58_mesh_32: THREE.Mesh;
    mesh58_mesh_33: THREE.Mesh;
    mesh58_mesh_34: THREE.Mesh;
    mesh58_mesh_35: THREE.Mesh;
    mesh94_mesh: THREE.Mesh;
    mesh94_mesh_1: THREE.Mesh;
    mesh94_mesh_2: THREE.Mesh;
    mesh94_mesh_3: THREE.Mesh;
    mesh94_mesh_4: THREE.Mesh;
    mesh94_mesh_5: THREE.Mesh;
    mesh94_mesh_6: THREE.Mesh;
    mesh94_mesh_7: THREE.Mesh;
    mesh94_mesh_8: THREE.Mesh;
    mesh94_mesh_9: THREE.Mesh;
    mesh94_mesh_10: THREE.Mesh;
    mesh94_mesh_11: THREE.Mesh;
    mesh94_mesh_12: THREE.Mesh;
    mesh94_mesh_13: THREE.Mesh;
    mesh94_mesh_14: THREE.Mesh;
    mesh94_mesh_15: THREE.Mesh;
    mesh94_mesh_16: THREE.Mesh;
    mesh94_mesh_17: THREE.Mesh;
    mesh94_mesh_18: THREE.Mesh;
    mesh94_mesh_19: THREE.Mesh;
    mesh94_mesh_20: THREE.Mesh;
    mesh94_mesh_21: THREE.Mesh;
    mesh94_mesh_22: THREE.Mesh;
    mesh94_mesh_23: THREE.Mesh;
    mesh94_mesh_24: THREE.Mesh;
    mesh94_mesh_25: THREE.Mesh;
    mesh94_mesh_26: THREE.Mesh;
    mesh94_mesh_27: THREE.Mesh;
    mesh94_mesh_28: THREE.Mesh;
    mesh94_mesh_29: THREE.Mesh;
    mesh124_mesh: THREE.Mesh;
    mesh124_mesh_1: THREE.Mesh;
    mesh124_mesh_2: THREE.Mesh;
    mesh124_mesh_3: THREE.Mesh;
    mesh124_mesh_4: THREE.Mesh;
    mesh129_mesh: THREE.Mesh;
    mesh129_mesh_1: THREE.Mesh;
    mesh129_mesh_2: THREE.Mesh;
    mesh129_mesh_3: THREE.Mesh;
    mesh129_mesh_4: THREE.Mesh;
    mesh129_mesh_5: THREE.Mesh;
    mesh129_mesh_6: THREE.Mesh;
    mesh129_mesh_7: THREE.Mesh;
    mesh129_mesh_8: THREE.Mesh;
    mesh129_mesh_9: THREE.Mesh;
    mesh129_mesh_10: THREE.Mesh;
    mesh129_mesh_11: THREE.Mesh;
    mesh129_mesh_12: THREE.Mesh;
    mesh129_mesh_13: THREE.Mesh;
    mesh129_mesh_14: THREE.Mesh;
    mesh129_mesh_15: THREE.Mesh;
    mesh129_mesh_16: THREE.Mesh;
    mesh129_mesh_17: THREE.Mesh;
    mesh129_mesh_18: THREE.Mesh;
    mesh129_mesh_19: THREE.Mesh;
    mesh129_mesh_20: THREE.Mesh;
    mesh129_mesh_21: THREE.Mesh;
    mesh129_mesh_22: THREE.Mesh;
    mesh129_mesh_23: THREE.Mesh;
    mesh129_mesh_24: THREE.Mesh;
    mesh129_mesh_25: THREE.Mesh;
    mesh129_mesh_26: THREE.Mesh;
    mesh129_mesh_27: THREE.Mesh;
    mesh129_mesh_28: THREE.Mesh;
    mesh129_mesh_29: THREE.Mesh;
    mesh129_mesh_30: THREE.Mesh;
    mesh129_mesh_31: THREE.Mesh;
    mesh129_mesh_32: THREE.Mesh;
    mesh129_mesh_33: THREE.Mesh;
    mesh129_mesh_34: THREE.Mesh;
    mesh129_mesh_35: THREE.Mesh;
    mesh129_mesh_36: THREE.Mesh;
    mesh129_mesh_37: THREE.Mesh;
    mesh129_mesh_38: THREE.Mesh;
    mesh129_mesh_39: THREE.Mesh;
    mesh129_mesh_40: THREE.Mesh;
    mesh129_mesh_41: THREE.Mesh;
    mesh129_mesh_42: THREE.Mesh;
    mesh129_mesh_43: THREE.Mesh;
    mesh129_mesh_44: THREE.Mesh;
    mesh129_mesh_45: THREE.Mesh;
    mesh129_mesh_46: THREE.Mesh;
    mesh176_mesh: THREE.Mesh;
    mesh176_mesh_1: THREE.Mesh;
    mesh176_mesh_2: THREE.Mesh;
    mesh176_mesh_3: THREE.Mesh;
    mesh176_mesh_4: THREE.Mesh;
    mesh176_mesh_5: THREE.Mesh;
    mesh176_mesh_6: THREE.Mesh;
    mesh176_mesh_7: THREE.Mesh;
    mesh176_mesh_8: THREE.Mesh;
    mesh176_mesh_9: THREE.Mesh;
    mesh176_mesh_10: THREE.Mesh;
    mesh176_mesh_11: THREE.Mesh;
    mesh176_mesh_12: THREE.Mesh;
  };
  materials: {
    ["0.737255_0.937255_0.917647_0.000000_0.662745"]: THREE.MeshStandardMaterial;
    ["0.752941_0.619608_0.439216_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.874510_0.819608_0.678431_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.964706_0.964706_0.964706_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.376471_0.415686_0.450980_0.000000_0.000000"]: THREE.MeshStandardMaterial;
    ["0.850980_0.756863_0.866667_0.000000_0.000000"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/hovercraft_mk1.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <group position={[0, -0.043, 0.087]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh0_mesh.geometry}
          material={materials["0.737255_0.937255_0.917647_0.000000_0.662745"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh0_mesh_1.geometry}
          material={materials["0.737255_0.937255_0.917647_0.000000_0.662745"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh0_mesh_2.geometry}
          material={materials["0.737255_0.937255_0.917647_0.000000_0.662745"]}
        />
      </group>
      <group position={[0, -0.043, 0.087]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_1.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_2.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_3.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_4.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_5.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_6.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_7.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_8.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_9.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_10.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_11.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_12.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_13.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_14.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_15.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_16.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_17.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_18.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_19.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_20.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_21.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_22.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_23.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_24.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_25.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_26.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_27.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_28.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_29.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_30.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_31.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_32.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_33.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_34.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_35.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_36.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_37.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_38.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_39.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_40.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_41.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_42.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_43.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_44.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_45.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_mesh_46.geometry}
          material={materials["0.376471_0.415686_0.450980_0.000000_0.000000"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_1.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_2.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_3.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_4.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_5.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_6.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_7.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_8.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_9.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_10.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_11.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh3_mesh_12.geometry}
        material={materials["0.752941_0.619608_0.439216_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh16_mesh.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh16_mesh_1.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh16_mesh_2.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh16_mesh_3.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh16_mesh_4.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh16_mesh_5.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_1.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_2.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_3.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_4.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_5.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_6.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_7.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_8.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_9.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_10.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_11.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_12.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_13.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_14.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_15.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_16.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_17.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_18.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_19.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_20.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_21.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_22.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_23.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_24.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_25.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_26.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_27.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_28.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh22_mesh_29.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh52_mesh.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh52_mesh_1.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh52_mesh_2.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh52_mesh_3.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh52_mesh_4.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh52_mesh_5.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_1.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_2.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_3.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_4.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_5.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_6.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_7.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_8.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_9.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_10.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_11.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_12.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_13.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_14.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_15.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_16.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_17.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_18.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_19.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_20.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_21.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_22.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_23.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_24.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_25.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_26.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_27.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_28.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_29.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_30.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_31.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_32.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_33.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_34.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh58_mesh_35.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_1.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_2.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_3.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_4.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_5.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_6.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_7.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_8.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_9.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_10.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_11.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_12.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_13.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_14.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_15.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_16.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_17.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_18.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_19.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_20.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_21.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_22.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_23.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_24.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_25.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_26.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_27.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_28.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh94_mesh_29.geometry}
        material={materials["0.874510_0.819608_0.678431_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh124_mesh.geometry}
        material={materials["0.964706_0.964706_0.964706_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh124_mesh_1.geometry}
        material={materials["0.964706_0.964706_0.964706_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh124_mesh_2.geometry}
        material={materials["0.964706_0.964706_0.964706_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh124_mesh_3.geometry}
        material={materials["0.964706_0.964706_0.964706_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh124_mesh_4.geometry}
        material={materials["0.964706_0.964706_0.964706_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_1.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_2.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_3.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_4.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_5.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_6.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_7.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_8.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_9.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_10.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_11.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh176_mesh_12.geometry}
        material={materials["0.850980_0.756863_0.866667_0.000000_0.000000"]}
      />
    </group>
  );
}

useGLTF.preload("/models/hovercraft_mk1.gltf");
